name: Python Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run unit tests
        run: |
          # Navigate to the backend directory
          cd ${{ github.workspace }}/src/backend || cd .
          docker build -t backend-tests .
          docker run --rm backend-tests python -m unittest discover -v

      - name: Run integration tests with Docker Compose
        run: |
          # Install curl for healthchecks
          sudo apt-get update
          sudo apt-get install -y curl

          # Navigate to the repository root directory
          cd ${{ github.workspace }}

          # Run tests using docker-compose
          docker-compose up --build --exit-code-from tests tests
